# Generated by Django 4.0.6 on 2022-08-01 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='haspartLabel',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='haspart'),
        ),
    ]
