# Generated by Django 4.0.6 on 2022-08-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_enterprise_haspartlabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='haspartLabel',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Parte de'),
        ),
    ]
