# Generated by Django 4.0.6 on 2022-08-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_rename_haspartlabel_enterprise_haspart'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='created',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Fecha de creacion'),
        ),
    ]
